server:
  port: 8080
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-dhyleqtw.sql.tencentcdb.com:28177/activity
    username: root
    password: Flash666
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#logging:
#  level:
#    com.baomidou.mybatisplus: DEBUG
#    com.dragonsoft.demojar.mapper: DEBUG